spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                - id: service
                  uri: http://localhost:8071
                  predicates:
                    - Path= /api/v1/**

server:
    port: 8070

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true

